version: "3.3"

services:
 
 spring-cloud-config-server: 
        image: rajeevshukla/spring-cloud-config-server
        container_name: spring_cloud_config_server
        ports: 
          - "8888:8888"
        environment:
          - "SPRING_PROFILES_ACTIVE=prod"
 
 netflix-eureka-naming-server:
        image: rajeevshukla/netflix-eureka-naming-server
        container_name: netflix_eureka_naming_server
        ports:
         - "8761:8761"
        environment:
         - "SPRING_PROFILES_ACTIVE=prod"
 
 rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
    - /root/rabbitmq_data:/var/lib/rabbitmq
 mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes: 
    - /root/mysql_data:/var/lib/mysql
    
 spring-boot-email:
      image: rajeevshukla/email-service
      depends_on: 
       - rabbitmq
       - spring-cloud-config-server 
       - netflix-eureka-naming-server
      ports: 
      - "8089:8089"
      links: 
       - rabbitmq
       - spring-cloud-config-server 
       - netflix-eureka-naming-server
      deploy: 
        mode: replicated
        replicas: 1
        restart_policy:
        condition: on-failure
      environment:
       - "SPRING_PROFILES_ACTIVE=prod"
  
 spring-boot-user-registration:
      image: rajeevshukla/user-registration-service
      depends_on: 
       - mysql
       - rabbitmq
       - spring-cloud-config-server  
       - netflix-eureka-naming-server
      ports: 
      - "8080:8080"
      links: 
       - mysql
       - rabbitmq
       - spring-cloud-config-server 
       - netflix-eureka-naming-server
      deploy: 
        mode: replicated
        replicas: 1
        restart_policy:
        condition: on-failure
      environment:
       - "SPRING_PROFILES_ACTIVE=prod"
       
 netflix-cloud-zuul-server:
        image: rajeevshukla/netflix-cloud-zuul-server
        ports:
         - "8889:8889"
        depends_on: 
        - netflix-eureka-naming-server 
        links:
         - netflix-eureka-naming-server
        environment:
         - "SPRING_PROFILES_ACTIVE=prod"
  