version: "3.3"

services:
 
 spring-cloud-config-server: 
        image: rajeevshukla/spring-cloud-config-server
        ports: 
          - "8888:8888"
        environment:
          - "SPRING_PROFILES_ACTIVE=prod"
 
 netflix-eureka-naming-server:
        image: rajeevshukla/netflix-eureka-naming-server
        ports:
         - "8761:8761"
        environment:
         - "SPRING_PROFILES_ACTIVE=prod"
 
 rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
    - /root/rabbitmq_data:/var/lib/rabbitmq
 mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes: 
    - /root/mysql_data:/var/lib/mysql
    
 spring-boot-email:
      image: rajeevshukla/email-service
      depends_on: 
       - rabbitmq
       - spring-cloud-config-server 
       - netflix-eureka-naming-server
       - zipkin
      ports: 
      - "8089:8089"
      links: 
       - rabbitmq
       - spring-cloud-config-server 
       - netflix-eureka-naming-server
       - zipkin
      #deploy: 
       # mode: replicated
        #replicas: 2
      command: ["./wait-for-it.sh"," spring-cloud-config-server:8888","--", "./wait-for-it.sh", "rabbitmq:15672","--","./wait-for-it.sh", "netflix-eureka-naming-server:8761","--", "java","-jar","email-service-0.0.1-SNAPSHOT.jar" ]
      environment:
       - "SPRING_PROFILES_ACTIVE=prod"
  
 spring-boot-user-registration:
      image: rajeevshukla/user-registration-service
      depends_on: 
       - mysql
       - rabbitmq
       - spring-cloud-config-server  
       - netflix-eureka-naming-server
       - zipkin
      ports: 
      - "8080:8080"
      links: 
       - mysql
       - rabbitmq
       - spring-cloud-config-server 
       - netflix-eureka-naming-server
       - zipkin
   #   deploy: 
    #    mode: replicated
     #   replicas: 2
      command: ["./wait-for-it.sh","spring-cloud-config-server:8888","--","./wait-for-it.sh", "rabbitmq:15672","--", "./wait-for-it.sh", "mysql:3306","--","./wait-for-it.sh", "netflix-eureka-naming-server:8761", "--","java", "-jar", "user-registration-service-0.0.1-SNAPSHOT.jar"]
      environment:
       - "SPRING_PROFILES_ACTIVE=prod"
       
 netflix-cloud-zuul-server:
        image: rajeevshukla/netflix-cloud-zuul-server
        ports:
         - "8889:8889"
        depends_on: 
        - netflix-eureka-naming-server
        - zipkin
        links:
         - netflix-eureka-naming-server
         - zipkin
        command: ["./wait-for-it.sh", "netflix-eureka-naming-server:8761", "--","java", "-jar", "netflix-cloud-zuul-server-0.0.1-SNAPSHOT.jar"] 
        environment:
         - "SPRING_PROFILES_ACTIVE=prod"
 zipkin: 
       image: openzipkin/zipkin
       ports:
       - "9411:9411"
       