version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
    - /root/rabbitmq_data:/var/lib/rabbitmq
  
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes: 
    - /root/mysql_data:/var/lib/rabbitmq
    
  
  spring-boot-email:
      image: rajeevshukla/email-services
      depends_on: 
        - rabbitmq
        - spring_cloud_config_server 
        - netflix_eureka_naming_server
      ports: 
      - "8089:8089"
      links: 
       - rabbitmq 
       - spring_cloud_config_server 
       - netflix_eureka_naming_server
      deploy: 
        mode: replicated
        replicas: 2
      environment:
       - "SPRING_PROFILES_ACTIVE=prod"
  
  spring-boot-user-registration:
      image: rajeevshukla/user-registration-service
      depends_on: 
        - mysql
        - rabbitmq
      ports: 
      - "8080:8080"
      links: 
       - mysql
       - rabbitmq
       - spring_cloud_config_server 
       - netflix_eureka_naming_server
      deploy: 
        mode: replicated
        replicas: 2
      environment:
       - "SPRING_PROFILES_ACTIVE=prod"
       
  spring-cloud-config-server: 
        image: rajeevshukla/spring-cloud-config-server
        container_name: spring_cloud_config_server
        ports: 
          - ""
        links: 
          - netflix_eureka_naming_server
        environment:
          - "SPRING_PROFILES_ACTIVE=prod"
  
  netflix-cloud-zuul-server:
        image: rajeevshukla/netflix-cloud-zuul-server
        ports:
         - ""
        links:
         - netflix_eureka_naming_server
        environment:
         - "SPRING_PROFILES_ACTIVE=prod"
   
  netflix-eureka-naming-server:
        image: rajeevshukla/netflix-eureka-naming-server
        container_name: netflix_eureka_naming_server
        ports:
         - ""
        links:
         - 
        environment:
         - "SPRING_PROFILES_ACTIVE=prod"
         
        