version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
    - /root/rabbitmq_data:/var/lib/rabbitmq
  
  spring-boot:
      image: rajeevshukla/email-services
      ports: 
      - "8089:8089"
      links: 
       - rabbitmq 
       - spring-cloud-config-server
     # command: ["./wait-for-it.sh"," spring_cloud_config_server:8888", " rabbitmq:15672"]
      command: ["./wait-for-it.sh"," spring_cloud_config_server:8888","--","./wait-for-it.sh", " rabbitmq:15672","--", "./wait-for-it.sh", " netflix_eureka_naming_server:8761"]
      #deploy: 
       # mode: replicated
        #replicas: 2
      environment: 
       - "SPRING_PROFILES_ACTIVE=prod"
  spring-cloud-config-server: 
        image: rajeevshukla/spring-cloud-config-server
        container_name: spring_cloud_config_server
        ports: 
          - "8888:8888"
        environment:
          - "SPRING_PROFILES_ACTIVE=prod"
 