version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
    - /root/rabbitmq_data:/var/lib/rabbitmq
  
  spring-boot:
      image: rajeevshukla/email-services
      ports: 
      - "8080:8080"
      links: 
       - rabbitmq 
      deploy: 
        mode: replicated
        replicas: 2