version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
    - /root/rabbitmq_data:/var/lib/rabbitmq
  
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes: 
    - /root/mysql_data:/var/lib/mysql
  
  spring-boot:
      image: rajeevshukla/user-registration-service
      ports: 
      - "8080:8080"
      links: 
       - mysql
       - rabbitmq 
       - spring-cloud-config-server
     # command: ["./wait-for-it.sh"," spring_cloud_config_server:8888", " rabbitmq:15672"]
      command: ["./wait-for-it.sh"," spring_cloud_config_server:8888"]
      #deploy: 
       # mode: replicated
        #replicas: 2
      environment: 
       - "SPRING_PROFILES_ACTIVE=prod"
  spring-cloud-config-server: 
        image: rajeevshukla/spring-cloud-config-server
        container_name: spring_cloud_config_server
        ports: 
          - "8888:8888"
        environment:
          - "SPRING_PROFILES_ACTIVE=prod"
 