spring:
  application: 
   name: spring-cloud-gateway-server
  zipkin:
    enabled: true
    base-url: http://zipkin:9411
    service:
      name: ${spring.application.name} 
  sleuth:
    sampler:
      probability: 1
server:
  port: 8889
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
  
eureka:
  client:
    serviceUrl:
     defaultZone: http://netflix-eureka-naming-server:8761/eureka/
  instance:
     instance-id: ${spring.application.name}:${random.int[5000,6000]}
     preferIpAddress: true
     prefer-ip-address: true
 
 


# with this you can call any user-registration service URL with just passing localhost:8889/users/whetever you have on user-registration controller. 
#zuul.routes.user-registration-service.path=/users/*
#zuul.routes.user-registration-service.location=user-registration-service